#AGRADEÇO AO PROFESSOR DO CANAL DesCOMPlica, Oliba! PELOS ENSINAMENTOS :D
#PONTOS FLUTUANTES

#EXISTEM DOIS TIPOS DE PONTOS FLUTUANTES:
#Float: precisa de 1 coprocessador
#Double: precisa de 2 copressadores

#Para imprimir float, usa li $v0, 2

#UM PONTO FLUTUANTE DOUBLE DEVE SEMPRE SER GUARDADO EM UM REGISTRADOR PAR, POIS ELE OCUPA O ESPAÇO DE DOIS REGISTRADORES

.data
	msg: .asciiz "Forneça um número decimal: "
	zero: .double 0.0 #VOU PRECISAR DESSA CONSTANTE ZERO
	
.text
	#IMPRIMINDO A MENSAGEM PARA O USUÁRIO
	li $v0, 4
	la $a0, msg
	syscall
	
	#LENDO O NÚMERO
	li $v0, 7 #A INSTRUÇÃO li $v0 JUNTO COM O NÚMERO 7 SIGNIFICA QUE UM DOUBLE SERÁ LIDO
	syscall #O VALOR LIDO ESTARÁ EM $f0
	
	ldc1 $f2, zero #NO EXEMPLO ANTERIOR USAMOS O REGISTRADOR $f1 AQUI. MAS LEMBRE-SE: 
	#QUANDO SE TRABALHA COM DOUBLE, SEMPRE USAM-SE OS REGISTRADORES PARES
	add.d $f12, $f2, $f0 #PARA IMPRIMIR O DOUBLE, ELE PRECISA ESTAR NO REGISTRADOR $f12, COMO EU NÃO TENHO UMA
	#INSTRUÇÃO QUE FAÇA DIRETAMENTE ESSA PASSAGEM, EU SOMO O VALOR LIDO (QUE ESTÁ EM $f0) COM A CONSTANTE
	#ZERO (QUE ESTÁ EM $f2) E GUARDO NO REGISTRADOR $f12, CONSEGUINDO ASSIM FAZER ESSA MOVIMENTAÇÃO.
	
	#IMPRIMINDO O VALOR:
	li $v0, 3 #A INSTRUÇÃO li $v0 JUNTO COM O NÚMERO 3 SIGNIFICA QUE UM DOUBLE SERÁ IMPRESSO
	syscall
	